import React from 'react'
import { Admin, Resource, Login, Edit, TextInput, SimpleForm, required } from 'react-admin'
import { BrowserRouter, Route } from 'react-router-dom'
import authProvider from './authProvider'
import dataProvider from './dataProvider'
import { AppList, AppCreate, AppShow } from './apps'
import AppLayout from './AppLayout'

const MyLoginPage = () => <Login backgroundImage="" />
const ProfileEdit = (props: { staticContext: {} }) => {
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const { staticContext, ...sanitizedProps } = props
  return (
    <Edit
      /*
        As this component isn't loaded from a route generated by a <Resource>,
        I have to provide the id myself.
        As there is only one config for the current user, I decided to
        hard-code it here
      */
      id="profile"
      /*
        For the same reason, I need to provide the resource and basePath props
        which are required by the Edit component
      */

      resource="profile"
      basePath="/profile"
      redirect={false} // I don't need any redirection here, there's no list page
      /*
        I also customized the page title as it'll make more sense to the user
      */
      title="My profile"
      {...sanitizedProps}
    >
      <SimpleForm>
        <TextInput source="email"  />
        <TextInput source="tier" />
        <TextInput source="credit_cents" />
      </SimpleForm>
    </Edit>
  )
}

const customRoutes = [<Route key="profile" path="/profile" component={ProfileEdit} />]

const App = () => (
  <BrowserRouter>
    <Admin
      customRoutes={customRoutes}
      appLayout={AppLayout}
      loginPage={MyLoginPage}
      authProvider={authProvider}
      dataProvider={dataProvider}
    >
      <Resource name="apps" show={AppShow} list={AppList} create={AppCreate} />
      <Resource name="profile" />
    </Admin>
  </BrowserRouter>
)

export default App
