import React from 'react'
import { Show, SimpleShowLayout, TextField } from 'react-admin'
import { Elements, StripeProvider } from 'react-stripe-elements'
import CheckoutForm from './CheckoutForm'

const ProfileShow = (props: { staticContext: {} }) => {
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const { staticContext, ...sanitizedProps } = props
  return (
    <div>
      <Show
        /*
          As this component isn't loaded from a route generated by a <Resource>,
          I have to provide the id myself.
          As there is only one config for the current user, I decided to
          hard-code it here
        */
        id="profile"
        /*
          For the same reason, I need to provide the resource and basePath props
          which are required by the Edit component
        */

        resource="profile"
        basePath="/profile"
        redirect="" // I don't need any redirection here, there's no list page
        /*
          I also customized the page title as it'll make more sense to the user
        */
        title="My profile"
        {...sanitizedProps}
      >
        <SimpleShowLayout>
          <TextField source="email" />
          <TextField source="tier" />
          <TextField source="credit_cents" />
        </SimpleShowLayout>
      </Show>
      <StripeProvider apiKey="pk_test_6tMDkFKTz4N0wIFQZHuzOUyW">
        <div className="example">
          <h1>React Stripe Elements Example</h1>
          <Elements>
            // stripe parameter is injected automatically by StripeProvider, but 
            // typescript complains about it if I don't put something here
            <CheckoutForm stripe="hello" />
          </Elements>
        </div>
      </StripeProvider>
    </div>
  )
}

export default ProfileShow
