import React from 'react'
import { Show, SimpleShowLayout, TextField, Authenticated } from 'react-admin'
import PaymentMethod from './PaymentMethod'
import UpdatePaymentMethod from './UpdatePaymentMethod'
import Upgrade from './Upgrade'

const ProfileShow = (props: { staticContext: {} }) => {
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const { staticContext, ...sanitizedProps } = props
  return (
    <Authenticated>
      <Show
        /*
          As this component isn't loaded from a route generated by a <Resource>,
          I have to provide the id myself.
          As there is only one config for the current user, I decided to
          hard-code it here
        */
        id="profile"
        /*
          For the same reason, I need to provide the resource and basePath props
          which are required by the Edit component
        */

        resource="profile"
        basePath="/login"
        redirect="" // I don't need any redirection here, there's no list page
        /*
          I also customized the page title as it'll make more sense to the user
        */
        title="My profile"
        {...sanitizedProps}
      >
        <SimpleShowLayout>
          <TextField source="email" />
          <TextField source="tier" />
          <TextField source="credit_cents" />
          <PaymentMethod record={{ tier: 'override-me' }} />
          <UpdatePaymentMethod record={{ tier: 'override-me' }} />
          <Upgrade record={{ tier: 'override-me' }} />
        </SimpleShowLayout>
      </Show>
    </Authenticated>
  )
}

export default ProfileShow
